# References {.unnumbered}

## Achievement Standard

New Zealand Qualifications Authority (NZQA). (2024). *Achievement Standard
91946: Interpret and apply mathematical and statistical information in context.*
NZQA. <https://www.nzqa.govt.nz/nqfdocs/ncea-resource/achievements/2024/as91946.pdf>

## New Zealand Statistics Curriculum

Ministry of Education New Zealand. (2007). *The New Zealand Curriculum.*
Learning Media. <https://nzcurriculum.tki.org.nz>

Ministry of Education New Zealand. (2023). *Mathematics and Statistics —
Achievement Objectives.* <https://nzcurriculum.tki.org.nz/The-New-Zealand-Curriculum/Mathematics-and-statistics>

## Textbooks and Teaching Resources

Wild, C. J., & Seber, G. A. F. (2000). *Chance Encounters: A First Course
in Data Analysis and Inference.* Wiley.

Pfannkuch, M., & Wild, C. J. (2004). Towards an understanding of statistical
thinking. In D. Ben-Zvi & J. Garfield (Eds.), *The Challenge of Developing
Statistical Literacy, Reasoning and Thinking* (pp. 17–46). Kluwer Academic.

## Data Sources

Statistics New Zealand (Stats NZ). (2024). *Household Economic Survey.*
<https://www.stats.govt.nz>

CensusAtSchool New Zealand. (2024). *CensusAtSchool data.* University of
Auckland. <https://new.censusatschool.org.nz>

## Software

R Core Team. (2024). *R: A Language and Environment for Statistical Computing.*
R Foundation for Statistical Computing. <https://www.r-project.org>

Allaire, J. J., Teague, C., Scheidegger, C., Xie, Y., & Dervieux, C.
(2024). *Quarto* (Version 1.5). <https://quarto.org>

Wickham, H., et al. (2023). *ggplot2: Elegant Graphics for Data Analysis*
(3rd ed.). Springer. <https://ggplot2-book.org>

## Statistical Literacy

Huff, D. (1954). *How to Lie with Statistics.* W. W. Norton & Company.

Wheelan, C. (2013). *Naked Statistics: Stripping the Dread from the Data.*
W. W. Norton & Company.
